language: python
env:
  matrix:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=pypy
  global:
  - GITHUB_USERNAME="imhotepbot"
  - secure: Oziz2mESs97bcb4Z62UspS30gvjWViUcBrErqSLJ2cDqK7gpPOHMPNMwhLmnuTgjBjf4M+FhJRG6yasTM7bBtD6joVbsxnfNb5kRUehOeCBrlQcuQMVdlwR5EuvWAb17otIo7ILyZnd+9cRd3aR2HYtEjJuvHMG6GwaotWGZkAw=
install: pip install tox
script: tox
after_success:
  coveralls
