language: python
env:
  global:
  - GITHUB_USERNAME="imhotepbot"
  - secure: Oziz2mESs97bcb4Z62UspS30gvjWViUcBrErqSLJ2cDqK7gpPOHMPNMwhLmnuTgjBjf4M+FhJRG6yasTM7bBtD6joVbsxnfNb5kRUehOeCBrlQcuQMVdlwR5EuvWAb17otIo7ILyZnd+9cRd3aR2HYtEjJuvHMG6GwaotWGZkAw=
python:
- '2.6'
- '2.7'
install: pip install -r requirements.txt
script: py.test --cov . --cov-report term-missing
after_success: coveralls
